name: postgres_cadastro
services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ifood
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_ifood
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ifood.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:5050"

  jaeger_ifood:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.52
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

