global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ifood-cadastro'
    scrape_interval: 5s
    metrics_path: /q/metrics
    static_configs:
      - targets:
          - host.docker.internal:8080