create table localizacao
(
    id_localizacao bigint generated by default as identity
        primary key,
    nm_latitude    double precision,
    nm_longitude   double precision
);

create table restaurante
(
    id_restaurante             bigint generated by default as identity
        primary key,
    ds_cnpj                    varchar(255),
    ds_nome_proprietario       varchar(255),
    ds_nome_restaurante        varchar(255),
    dt_atualizacao             date,
    dt_criacao                 date,
    localizacao_id_localizacao bigint
        constraint uki1hkm9x6s9a1l7nto3609wacy
            unique
        constraint fkolnjx50jfgysx7cmf209vguf7
            references localizacao
);


create table prato
(
    id_prato       bigint generated by default as identity
        primary key,
    descricao      varchar(255),
    ds_nome_prato  varchar(255),
    nm_valor       numeric(38, 2),
    id_restaurante bigint
        constraint fkj74j9gjk32uduxnx4dq6ydwqx
            references restaurante
);